### ISSUE TITLE
Control unassigned cells

### ISSUE THREAD

**Issue by ViriatoII** [ImXman/MACA#2]
Hi,

The paper mentions unassigned cells but all my cells get assigned to a cluster. Is it a way of controlling how easy it is to be unassigned? Maybe some assignment probabilities?

Cheers,
Ricardo

**Comment by ViriatoII** [comment]
Found it, thanks!


```
scores, labels = maca.gene2cell(ad=ad,cell_markers=cell_markers)

scores
```

> <html><body>


  | hepatocytes | t-cells | kupffer cells | hepatic stellate cells
-- | -- | -- | -- | --
0 | 0.505414 | 0.0 | 1.200154 | 0.000000
1 | 1.000000 | 0.0 | 0.000000 | 0.000000
2 | 0.000000 | 0.0 | 0.000000 | 1.000000
3 | 0.540924 | 0.0 | 1.135471 | 0.000000


</body>
</html>

**Comment by ImXman** [comment]
Hi Viriatall,

I am glad that your problem solved.

It seems the "scores" only have 4 cell types (4 dimension). I would use PCA for visualization instead of UMAP.

Meanwhile, in the "singleMACA" function, you can set the argument "freq" to a higher value like 0.75. The default is 0.5. Maybe it can help you get more unassigned cells.
